FROM selenium/node-chrome

RUN sudo apt-get update -qqy \
  && sudo apt-get -qqy --no-install-recommends install -y net-tools

#==============================
# Scripts to run Selenium Node
#==============================
COPY custom_entry_point.sh /opt/bin/

CMD ["bash", "/opt/bin/custom_entry_point.sh"]
